# Generated by Django 3.2.5 on 2022-02-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pastes_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastes',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='pastes',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PasteTextAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pastes')),
            ],
            options={
                'ordering': ['-accessed'],
            },
        ),
    ]
